server:
  port: 6677 #服务端口
spring:
  application:
    name: yidu-microservice-api-gateway #指定服务名

eureka:
  client:
    register-with-eureka: true #是否将自己注册到Eureka服务中，默认为true
    fetch-registry: true #是否从Eureka中获取注册信息，默认为true
    service-url:
      defaultZone: http://127.0.0.1:8099/eureka/


# 路由规则
zuul:
  routes:
    product-service: #product-service这个名字是自己取的
      path: /product/** #配置请求URL的请求规则
      url: http://127.0.0.1:8088/yidu/product #真正的微服务地址 访问地址http://localhost:6677/product/1001
      #url: yidu-product-microService #加入eureka之后,可以使用服务ID 访问地址http://localhost:6677/product/yidu/product/1001

    #yidu-product-microService: /product/** #加入eureka之后,更加简单的配置